[package]
name = "advent-of-code-2022-09"
version = "0.1.0"
edition = "2021"
[[bin]]
name="09"
path="./09.rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

