[package]
name = "advent-of-code-2022-01"
version = "0.1.0"
edition = "2021"
[[bin]]
name="01"
path="./01.rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
