[package]
name = "advent-of-code-2022-08"
version = "0.1.0"
edition = "2021"
[[bin]]
name="08"
path="./08.rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

